### ISSUE TITLE
DFRNT link navigates to multiple pages

### ISSUE THREAD

**Issue by tech41** [dfrnt-com/support.dfrnt.tech#8] opened 2023-01-29 06:30 UTC
Starting from https://dfrnt.com/modeller/modeleditor, I click on DFRNT. It navigates to https://dfrnt.com/modeller/dataproduct.

Click it again, it navigates to https://dfrnt.com/modeller

Click it again, it navigates to the home page

<img width="317" alt="image" src="https://user-images.githubusercontent.com/66345289/215309073-f46c9eee-47b6-4a71-860c-df1aeeea90bd.png">
<img width="341" alt="image" src="https://user-images.githubusercontent.com/66345289/215309135-29af6fbd-d694-47b7-87d4-bf91ef897918.png">
<img width="494" alt="image" src="https://user-images.githubusercontent.com/66345289/215309227-bcef1fbd-51ab-4327-acde-1e09017d7377.png">
<img width="316" alt="image" src="https://user-images.githubusercontent.com/66345289/215309246-454ecbd9-4683-42a9-bd1b-317fbe3fd0fd.png">

**Comment by hoijnet** [comment] 2023-01-29 08:57
This is by design, the idea is to take oneself "up" step by step, first to the data product, then to the overall view, then to the homepage. Maybe the last step should not be there?

**Comment by tech41** [comment] 2023-01-30 06:30
Gotcha, thanks for explaining. It's an architecture I'm not familiar with but I can learn it. But FWIW generally I would prefer one link per page, it's more intuitive to me to know exactly where I'm going with each link. Or as an alternative to adding multiple more tabs, perhaps an up arrow or triangle to indicate that it takes you up a step? That might be helpful - I was not familiar enough with the material to know that I was traveling 'up'.

It is nice having a link to the website root - sometimes there are resources there that you're looking for.

**Comment by hoijnet** [comment] 2023-01-30 07:30
Initially it was only linked to the DFRNT homepage, and I felt that was out of context and changed it. The primary "up" navigation is supposed to be the breadcrumbs. I will consider if changing to navigate to the modeller root (assuming that is what it expected to do)?

**Comment by tech41** [comment] 2023-02-01 05:47
It might just be personal preference but I like having a link to the homepage - for example, as a way to navigate to the blog, or if I wanted to review the pricing plans.

Wherever it goes, IMHO it should always go to one place rather than switching. That was confusing and felt like a bug. But get some feedback from other people and see what they think :)

**Comment by hoijnet** [comment] 2023-02-04 20:50
After having pondered, I agree with you in that whilst useful for the one who knows it, it is not a proper UX. And, continuing to explore the topic, I realised navigating up should be a job for the breadcrumb which is missing in some places where the only "back" option remained hidden with the logo navigation that was unintuitive.

The link should be clear where it takes you! I will make the necessary updates and take your queue to point to the homepage, but as it revealed a deeper UX issue, I will dig deeper to solve it properly!

Thanks again for opening this issue, keeping it open until resolved. This helped fixing some deeper navigation issues too 🙏

**Comment by hoijnet** [comment] 2023-02-17 23:27
This is now fixed in the development branch and will be in the next release. It will point to `/modeller` as an easy and predictable button to go to a known starting point. Also, there will be a more intuitive way to get back to the current data product overview page which was the second function of the button.

**Closed as completed by hoijnet** 2023-02-17 23:27 UTC
